
// src/app/admin/micro-apps/initial-data.ts
import type { MicroApp } from '@/types/micro-app';

export const mockMicroApps: MicroApp[] = [
  {
    id: 'autopilot_v1',
    internalName: 'autopilot',
    displayName: 'Autopilot Workflow Builder',
    icon: 'Workflow', // Placeholder for Lucide icon name
    description: 'Visually create and manage multi-step AI-powered automations and task chains.',
    category: 'Automation',
    status: 'enabled',
    tags: ['workflow', 'ai', 'visual-editor', 'automation', 'low-code'],
    agentDependencies: ['Orion', 'Proxy'],
    authRequired: true,
    isVisible: true,
    requiresSubscription: true, // Added flag
    monetization: { 
        enabled: true, 
        price: 29, 
        billingCycle: 'monthly', 
        billingAgent: 'BillingProxy',
        pricingTierId: 'tier_pro_monthly',
        stripeProductId: 'prod_XyZ123Abc',
        accessControlFlags: ['pro_tier_access']
    },
    flags: { isFeatured: true, requiresBetaFeature: false },
    version: '1.1.0',
    entryPoint: '/loom-studio?app=autopilot',
    deployableTo: ['loom-studio', 'dashboard'],
    permissionsRequired: ['agent:execute', 'workflow:create'],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'guardian_sec_v2.3',
    internalName: 'guardian-security-center',
    displayName: 'Guardian Security Center',
    icon: 'ShieldCheck',
    description: 'Monitor system threats, analyze security logs, and manage access controls.',
    category: 'Security',
    status: 'enabled',
    tags: ['security', 'monitoring', 'rbac', 'threat-detection'],
    agentDependencies: ['Aegis', 'LogSentinel'],
    authRequired: true,
    isVisible: true,
    requiresSubscription: false, // Example: core security app might be included
    monetization: null,
    flags: { systemInternal: true },
    version: '2.3.1',
    entryPoint: '/security',
    deployableTo: ['dedicated-tab'],
    permissionsRequired: ['security:admin', 'logs:view_sensitive'],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pulse_monitor_v0.9b',
    internalName: 'system-pulse',
    displayName: 'System Pulse Monitor',
    icon: 'RadioTower',
    description: 'Live overview of system health, agent activity, and key performance metrics.',
    category: 'Monitoring',
    status: 'beta',
    tags: ['monitoring', 'health', 'real-time', 'kpi'],
    agentDependencies: [],
    authRequired: true,
    isVisible: true,
    requiresSubscription: false,
    monetization: null,
    flags: { requiresBetaFeature: true },
    version: '0.9.0-beta',
    entryPoint: '/pulse',
    deployableTo: ['dedicated-tab', 'dashboard'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dev_tools_alpha',
    internalName: 'developer-sandbox',
    displayName: 'Developer Sandbox',
    icon: 'TerminalSquare',
    description: 'Experimental tools and features for NexOS developers. Use with caution.',
    category: 'Development',
    status: 'dev-only',
    tags: ['experimental', 'debug', 'tools'],
    agentDependencies: [],
    authRequired: true,
    isVisible: false, // Example of a not globally visible app
    requiresSubscription: false,
    monetization: null,
    flags: { isDevOnly: true },
    version: '0.1.0-alpha',
    deployableTo: ['none'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

    
