
// src/app/admin/micro-apps/initial-data.ts
import type { MicroApp } from '@/types/micro-app';

export const mockMicroApps: MicroApp[] = [
  {
    id: 'autopilot_v1',
    internalName: 'autopilot',
    displayName: 'Autopilot Workflow Builder',
    icon: 'Workflow', 
    description: 'Visually create and manage multi-step AI-powered automations and task chains.',
    category: 'Automation',
    status: 'enabled',
    tags: ['workflow', 'ai', 'visual-editor', 'automation', 'low-code'],
    agentDependencies: ['Orion', 'Proxy'],
    authRequired: true,
    isVisible: true,
    requiresSubscription: true, 
    monetization: { 
        enabled: true, 
        price: 29, 
        billingCycle: 'monthly', 
        billingAgent: 'BillingProxy',
        pricingTierId: 'tier_pro_monthly',
        stripeProductId: 'prod_XyZ123Abc',
        accessControlFlags: ['pro_tier_access']
    },
    flags: { isFeatured: true, requiresBetaFeature: false },
    version: '1.1.0',
    entryPoint: '/loom-studio?app=autopilot',
    deployableTo: ['loom-studio', 'dashboard'],
    permissionsRequired: ['agent:execute', 'workflow:create'],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'guardian_sec_v2.3',
    internalName: 'guardian-security-center',
    displayName: 'Guardian Security Center',
    icon: 'ShieldCheck',
    description: 'Monitor system threats, analyze security logs, and manage access controls.',
    category: 'Security',
    status: 'enabled',
    tags: ['security', 'monitoring', 'rbac', 'threat-detection'],
    agentDependencies: ['Aegis', 'LogSentinel'],
    authRequired: true,
    isVisible: true,
    requiresSubscription: false, 
    monetization: null,
    flags: { systemInternal: true },
    version: '2.3.1',
    entryPoint: '/security',
    deployableTo: ['dedicated-tab'],
    permissionsRequired: ['security:admin', 'logs:view_sensitive'],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pulse_monitor_v0.9b',
    internalName: 'system-pulse',
    displayName: 'System Pulse Monitor',
    icon: 'RadioTower',
    description: 'Live overview of system health, agent activity, and key performance metrics.',
    category: 'Monitoring',
    status: 'beta',
    tags: ['monitoring', 'health', 'real-time', 'kpi'],
    agentDependencies: [],
    authRequired: true,
    isVisible: true,
    requiresSubscription: false,
    monetization: null,
    flags: { requiresBetaFeature: true },
    version: '0.9.0-beta',
    entryPoint: '/pulse',
    deployableTo: ['dedicated-tab', 'dashboard'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dev_tools_alpha',
    internalName: 'developer-sandbox',
    displayName: 'Developer Sandbox',
    icon: 'TerminalSquare',
    description: 'Experimental tools and features for NexOS developers. Use with caution.',
    category: 'Development',
    status: 'dev-only',
    tags: ['experimental', 'debug', 'tools'],
    agentDependencies: [],
    authRequired: true,
    isVisible: false, 
    requiresSubscription: false,
    monetization: null,
    flags: { isDevOnly: true },
    version: '0.1.0-alpha',
    deployableTo: ['none'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  // New Dashboard Widget Micro-Apps
  {
    id: 'dashboard-widget-launchpad',
    internalName: 'dashboardLaunchpad',
    displayName: 'Workspace Launchpad',
    icon: 'Rocket',
    description: 'Quickly launch common actions and studio environments.',
    category: 'Dashboard Widget',
    status: 'enabled',
    tags: ['dashboard', 'quick-actions'],
    agentDependencies: [],
    authRequired: false,
    isVisible: true,
    monetization: null,
    flags: { systemInternal: true },
    version: '1.0.0',
    componentKey: 'workspaceLaunchpadWidget',
    defaultLayout: {
      lg: { x: 0, y: 0, w: 12, h: 4, minW: 6, minH: 3 },
      md: { x: 0, y: 0, w: 10, h: 4, minW: 5, minH: 3 },
      sm: { x: 0, y: 0, w: 6, h: 4, minW: 3, minH: 3 },
    },
    deployableTo: ['dashboard'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dashboard-widget-activity-feed',
    internalName: 'dashboardActivityFeed',
    displayName: 'Recent Activity Feed',
    icon: 'Activity',
    description: 'Displays recent system and agent activities.',
    category: 'Dashboard Widget',
    status: 'enabled',
    tags: ['dashboard', 'logs', 'feed'],
    agentDependencies: [],
    authRequired: false,
    isVisible: true,
    monetization: null,
    flags: { systemInternal: true },
    version: '1.0.0',
    componentKey: 'activityFeedWidget',
    defaultLayout: {
      lg: { x: 0, y: 4, w: 6, h: 8, minW: 3, minH: 5 },
      md: { x: 0, y: 4, w: 5, h: 8, minW: 3, minH: 5 },
      sm: { x: 0, y: 4, w: 6, h: 7, minW: 3, minH: 4 },
    },
    deployableTo: ['dashboard'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dashboard-widget-agent-presence',
    internalName: 'dashboardAgentPresence',
    displayName: 'Live Agent Presence',
    icon: 'Cpu',
    description: 'Shows the status and load of active AI agents.',
    category: 'Dashboard Widget',
    status: 'enabled',
    tags: ['dashboard', 'agents', 'monitoring'],
    agentDependencies: [],
    authRequired: false,
    isVisible: true,
    monetization: null,
    flags: { systemInternal: true },
    version: '1.0.0',
    componentKey: 'liveAgentPresenceWidget',
    defaultLayout: {
      lg: { x: 6, y: 4, w: 6, h: 8, minW: 3, minH: 5 },
      md: { x: 5, y: 4, w: 5, h: 8, minW: 3, minH: 5 },
      sm: { x: 0, y: 11, w: 6, h: 7, minW: 3, minH: 4 },
    },
    deployableTo: ['dashboard'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dashboard-widget-available-apps',
    internalName: 'dashboardAvailableApps',
    displayName: 'Available Micro-Apps',
    icon: 'LayoutGrid',
    description: 'Grid of deployable micro-applications from the registry.',
    category: 'Dashboard Widget',
    status: 'enabled',
    tags: ['dashboard', 'apps', 'launchpad'],
    agentDependencies: [],
    authRequired: false,
    isVisible: true,
    monetization: null,
    flags: { systemInternal: true },
    version: '1.0.0',
    componentKey: 'availableMicroAppsWidget',
    defaultLayout: {
      lg: { x: 0, y: 12, w: 12, h: 6, minW: 6, minH: 4 },
      md: { x: 0, y: 12, w: 10, h: 6, minW: 5, minH: 4 },
      sm: { x: 0, y: 18, w: 6, h: 7, minW: 4, minH: 4 },
    },
    deployableTo: ['dashboard'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
    